net.Receive("KEYBIND_SelectProfile", function(len, ply)
    local selectedProfile = net.ReadString()
    hook.Run("KEYBIND_ProfileSelected", ply, selectedProfile)
    net.Start("KEYBIND_SelectedProfile")
    net.WriteString(selectedProfile)
    net.Send(ply)
end)
